

////////////////////////////////////////////////////////////////////////////////
// Package: led_controller_avmm_pkg
// Generated by ipcraft SystemVerilog Generator
////////////////////////////////////////////////////////////////////////////////

`timescale 1ns / 1ps

package led_controller_avmm_pkg;

  ////////////////////////////////////////////////////////////////////////////
  // Constants
  ////////////////////////////////////////////////////////////////////////////
  localparam int C_DATA_WIDTH = 32;
  localparam int C_ADDR_WIDTH = 4;
  localparam int C_REG_WIDTH  = 4;  // Bytes per register

  ////////////////////////////////////////////////////////////////////////////
  // Register Address Map (byte offset, matches the resolved memory map and
  // the generated component.xml -- never derived from declaration order)
  ////////////////////////////////////////////////////////////////////////////
  localparam logic [C_ADDR_WIDTH-1:0] REG_VERSION_ADDR = 0;  // addr 00
  localparam logic [C_ADDR_WIDTH-1:0] REG_LED_PATTERN_ADDR = 4;  // addr 04
  localparam logic [C_ADDR_WIDTH-1:0] REG_EVENTS_ADDR = 8;  // addr 08

  ////////////////////////////////////////////////////////////////////////////
  // Register Field Structs and Conversion Functions
  ////////////////////////////////////////////////////////////////////////////

  // VERSION register fields
  typedef struct packed {
    logic [7:0] minor;  // bits 7:0
    logic [7:0] major;  // bits 15:8
  } version_t;

  // Pack VERSION fields into a 32-bit bus word
  function automatic logic [C_DATA_WIDTH-1:0] pack_version(input version_t reg_in);
    logic [C_DATA_WIDTH-1:0] slv;
    slv = '0;
    slv[7:0] = reg_in.minor;
    slv[15:8] = reg_in.major;
    return slv;
  endfunction

  // Unpack a 32-bit bus word into VERSION fields
  function automatic version_t unpack_version(input logic [C_DATA_WIDTH-1:0] slv);
    version_t reg_out;
    reg_out.minor = slv[7:0];
    reg_out.major = slv[15:8];
    return reg_out;
  endfunction

  // LED_PATTERN register fields
  typedef struct packed {
    logic [7:0] pattern;  // bits 7:0
  } led_pattern_t;

  // Pack LED_PATTERN fields into a 32-bit bus word
  function automatic logic [C_DATA_WIDTH-1:0] pack_led_pattern(input led_pattern_t reg_in);
    logic [C_DATA_WIDTH-1:0] slv;
    slv = '0;
    slv[7:0] = reg_in.pattern;
    return slv;
  endfunction

  // Unpack a 32-bit bus word into LED_PATTERN fields
  function automatic led_pattern_t unpack_led_pattern(input logic [C_DATA_WIDTH-1:0] slv);
    led_pattern_t reg_out;
    reg_out.pattern = slv[7:0];
    return reg_out;
  endfunction

  // EVENTS register fields
  typedef struct packed {
    logic        heartbeat_active;  // bit 0
    logic        heartbeat_toggled;  // bit 1
  } events_t;

  // Pack EVENTS fields into a 32-bit bus word
  function automatic logic [C_DATA_WIDTH-1:0] pack_events(input events_t reg_in);
    logic [C_DATA_WIDTH-1:0] slv;
    slv = '0;
    slv[0] = reg_in.heartbeat_active;
    slv[1] = reg_in.heartbeat_toggled;
    return slv;
  endfunction

  // Unpack a 32-bit bus word into EVENTS fields
  function automatic events_t unpack_events(input logic [C_DATA_WIDTH-1:0] slv);
    events_t reg_out;
    reg_out.heartbeat_active = slv[0];
    reg_out.heartbeat_toggled = slv[1];
    return reg_out;
  endfunction

  // W1C event-pulse struct types (hardware drives a 1-cycle strobe to set a sticky bit)
  // Hardware-driven value-port struct types: live values for read-only fields
  // mixed into an otherwise SW-writable register (includes CoS-monitored
  // fields, which are always mixed by construction).

  // EVENTS hardware-driven field values
  typedef struct packed {
    logic        heartbeat_active;  // hardware-driven, read-only in EVENTS
  } events_val_t;

  ////////////////////////////////////////////////////////////////////////////
  // Aggregate Register Structs (for clean port interface)
  ////////////////////////////////////////////////////////////////////////////

  // SW -> HW: Registers written by software, read by hardware
  typedef struct packed {
    led_pattern_t led_pattern;
    events_t events;
  } regs_sw2hw_t;

  // HW -> SW: Status registers (RO) + W1C/SC event pulses + hardware-driven value ports
  typedef struct packed {
    version_t version;
    events_val_t events_val;  // hardware-driven values for EVENTS
  } regs_hw2sw_t;

endpackage : led_controller_avmm_pkg
