


////////////////////////////////////////////////////////////////////////////////
// Module: led_controller_avmm_regs
// Description: Register bank with software/hardware access interface
// Generated by ipcraft SystemVerilog Generator
//
// This is a bus-agnostic register bank that provides:
// - Register storage for SW-writable registers
// - Clean interface for hardware logic access
//
// Connect to a bus wrapper (AXI-Lite, Avalon-MM, etc.) for host access.
////////////////////////////////////////////////////////////////////////////////
`timescale 1ns / 1ps


module led_controller_avmm_regs
  import led_controller_avmm_pkg::*;
(
  // Clock and reset
  input  logic clk,
  input  logic rst,

  // Write interface (from bus wrapper)
  input  logic                          wr_en,
  input  logic [C_ADDR_WIDTH-1:0]       wr_addr,
  input  logic [C_DATA_WIDTH-1:0]       wr_data,
  input  logic [(C_DATA_WIDTH/8)-1:0]   wr_strb,

  // Read interface (from bus wrapper)
  input  logic                          rd_en,
  input  logic [C_ADDR_WIDTH-1:0]       rd_addr,
  output logic [C_DATA_WIDTH-1:0]       rd_data,
  output logic                          rd_valid,
  // Register interface to core logic
  output regs_sw2hw_t regs_out,  // SW-writable registers (to core)
  input  regs_hw2sw_t regs_in   // HW status registers + W1C event pulses + CoS values (from core)
);

  // Internal register storage
  regs_sw2hw_t regs;

  // Read data pipeline
  logic [C_DATA_WIDTH-1:0] rd_data_int;
  logic                    rd_valid_int;

  // Shadow registers and CoS pulse signals for change-of-state detection
  logic        events_heartbeat_active_shadow;
  logic        events_heartbeat_toggled_cos;

  // Apply write strobe: merge new bytes from wr_data into existing word
  function automatic logic [C_DATA_WIDTH-1:0] apply_wstrb(
    input logic [C_DATA_WIDTH-1:0]     old_data,
    input logic [C_DATA_WIDTH-1:0]     new_data,
    input logic [(C_DATA_WIDTH/8)-1:0] wstrb
  );
    logic [C_DATA_WIDTH-1:0] result;
    result = old_data;
    for (int i = 0; i < C_DATA_WIDTH/8; i++) begin
      if (wstrb[i]) result[i*8 +: 8] = new_data[i*8 +: 8];
    end
    return result;
  endfunction

  // Output register values to core
  assign regs_out  = regs;
  assign rd_data   = rd_data_int;
  assign rd_valid  = rd_valid_int;

  // Combinatorial CoS pulse detection (current value vs shadow)
  assign events_heartbeat_toggled_cos = (regs_in.events_val.heartbeat_active !== events_heartbeat_active_shadow);

  ////////////////////////////////////////////////////////////////////////////
  // Write Process
  ////////////////////////////////////////////////////////////////////////////
  always_ff @(posedge clk) begin : p_write
    if (rst) begin
      regs.led_pattern.pattern <= 0;
      regs.events.heartbeat_active <= 0;
      regs.events.heartbeat_toggled <= 0;
      // Shadow registers reset to the monitored field's own reset value, so
      // the first post-reset comparison is always a match (no spurious
      // change-of-state event; also removes the undefined-power-up-state
      // risk on real hardware, since this is now an explicit sync reset).
      events_heartbeat_active_shadow <= 0;
    end else begin
      // Shadow register updates (capture monitored field values every clock)
      events_heartbeat_active_shadow <= regs_in.events_val.heartbeat_active;

      // W1C arbitration: hardware event-set has priority over CPU Write-1-to-Clear.
      // Runs every clock cycle so no pulse is missed even when the CPU is not writing.
      // CoS W1C arbitration (internally generated change-of-state pulse)
      if (events_heartbeat_toggled_cos) begin
        regs.events.heartbeat_toggled <= 1'b1;
      end else if (wr_en && wr_addr == REG_EVENTS_ADDR
                   && wr_strb[0] && wr_data[1]) begin
        regs.events.heartbeat_toggled <= 1'b0;
      end
      if (wr_en) begin
        unique case (wr_addr)
          REG_LED_PATTERN_ADDR: regs.led_pattern <= unpack_led_pattern(apply_wstrb(pack_led_pattern(regs.led_pattern), wr_data, wr_strb));
          default: ;
        endcase
      end
    end
  end

  ////////////////////////////////////////////////////////////////////////////
  // Read Process
  ////////////////////////////////////////////////////////////////////////////
  always_ff @(posedge clk) begin : p_read
    rd_valid_int <= 1'b0;
    if (rst) begin
      rd_data_int  <= '0;
      rd_valid_int <= 1'b0;
    end else if (rd_en) begin
      rd_valid_int <= 1'b1;
      unique case (rd_addr)
        REG_VERSION_ADDR: rd_data_int <= pack_version(regs_in.version);
        REG_LED_PATTERN_ADDR: rd_data_int <= pack_led_pattern(regs.led_pattern);
        REG_EVENTS_ADDR: begin
          begin : blk_rd_events
            logic [C_DATA_WIDTH-1:0] v;
            v = '0;
            v[0] = regs_in.events_val.heartbeat_active;
            rd_data_int <= v;
          end
        end
        default: rd_data_int <= '0;
      endcase
    end
  end

endmodule : led_controller_avmm_regs
