

////////////////////////////////////////////////////////////////////////////////
// Module: led_controller_avmm_avmm
// Description: Avalon-MM slave interface for register access
// Generated by ipcraft SystemVerilog Generator
//
// Register Map:
//   0000 : VERSION (read-only)
//   0004 : LED_PATTERN (read-write)
//   0008 : EVENTS (read-write-1-to-clear)
////////////////////////////////////////////////////////////////////////////////
`timescale 1ns / 1ps


module led_controller_avmm_avmm
  import led_controller_avmm_pkg::*;
(
  // Clock and reset
  input  logic clk,
  input  logic rst,

  // Avalon-MM Slave Interface
  input  logic [1:0]                        avs_address,
  input  logic                              avs_read,
  input  logic                              avs_write,
  input  logic [3:0]                        avs_byteenable,
  input  logic [31:0]                       avs_writedata,
  output logic [31:0]                       avs_readdata,

  // Register interface
  output regs_sw2hw_t regs_out,  // To core (SW-writable)
  input  regs_hw2sw_t regs_in   // From core (HW-writable / W1C pulses / CoS values)
);

  // Bus internal signals
  logic [C_ADDR_WIDTH-1:0]     address_int;
  logic                        read_int;
  logic                        write_int;
  logic [C_DATA_WIDTH-1:0]     writedata_int;
  logic [(C_DATA_WIDTH/8)-1:0] byteenable_int;
  logic [C_DATA_WIDTH-1:0]     readdata_int;
  logic                        readdatavalid_int;
  logic                        waitrequest_int;

  ////////////////////////////////////////////////////////////////////////////
  // Bus Interface Connections
  ////////////////////////////////////////////////////////////////////////////

  always_comb begin
    address_int    = avs_address[C_ADDR_WIDTH-1:0];
    read_int  = avs_read;
    write_int = avs_write;
    writedata_int  = avs_writedata;
    byteenable_int = avs_byteenable;
  end

  assign avs_readdata = readdata_int;

  // No wait states
  assign waitrequest_int = 1'b0;

  ////////////////////////////////////////////////////////////////////////////
  // Register Bank Instantiation
  ////////////////////////////////////////////////////////////////////////////
  led_controller_avmm_regs u_regs (
    .clk      (clk),
    .rst      (rst),
    .wr_en    (write_int),
    .wr_addr  (address_int),
    .wr_data  (writedata_int),
    .wr_strb  (byteenable_int),
    .rd_en    (read_int),
    .rd_addr  (address_int),
    .rd_data  (readdata_int),
    .rd_valid (readdatavalid_int),
    .regs_out (regs_out),
    .regs_in  (regs_in)
  );

endmodule : led_controller_avmm_avmm
