

////////////////////////////////////////////////////////////////////////////////
// Module: led_controller_avmm
// Description: Avalon-MM peripheral for the DE10-Nano LED demo. Drives 8 board LEDs from a software-writable pattern register and exposes a free-running heartbeat status bit with a sticky change-of-state event.

// Generated by ipcraft SystemVerilog Generator
////////////////////////////////////////////////////////////////////////////////
`timescale 1ns / 1ps


module led_controller_avmm import led_controller_avmm_pkg::*; (
  // Clock and reset
  input  logic clk,
  input  logic reset,

  // S_AVMM (SLAVE)
  input  logic [1:0]                        avs_address,
  input  logic                              avs_read,
  input  logic                              avs_write,
  input  logic [3:0]                        avs_byteenable,
  input  logic [31:0]                       avs_writedata,
  output logic [31:0]                       avs_readdata,

  // User ports
  output logic [7:0]                        led
);


  // Internal register signals
  regs_sw2hw_t regs_sw2hw;
  regs_hw2sw_t regs_hw2sw;

  ////////////////////////////////////////////////////////////////////////////
  // Bus Wrapper Instance
  ////////////////////////////////////////////////////////////////////////////
  led_controller_avmm_avmm u_avmm (
    .clk (clk),
    .rst (reset),
    .avs_address   (avs_address),
    .avs_read      (avs_read),
    .avs_write     (avs_write),
    .avs_byteenable(avs_byteenable),
    .avs_writedata (avs_writedata),
    .avs_readdata  (avs_readdata),
    .regs_out (regs_sw2hw),
    .regs_in  (regs_hw2sw)
  );

  ////////////////////////////////////////////////////////////////////////////
  // Core Logic Instance
  ////////////////////////////////////////////////////////////////////////////
  led_controller_avmm_core u_core (
    .clk (clk),
    .rst (reset),
    .regs_in  (regs_sw2hw),
    .regs_out (regs_hw2sw),
    .led(led)
  );

endmodule : led_controller_avmm
