"""
Memory-map YAML generator.

Produces .mm.yml content from an IpCore, either as a skeleton (when no register
data was discovered) or populated (when IP-XACT register data is available).
"""

from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

from ipcraft.model.core import IpCore


class MmYamlGenerator:
    """Generate a .mm.yml skeleton from an IpCore and/or parsed register data."""

    def generate(
        self,
        ip_core: IpCore,
        discovered_regs: Optional[List[Dict[str, Any]]] = None,
    ) -> str:
        """
        Generate .mm.yml YAML content.

        If *discovered_regs* is provided (from an IP-XACT memory map) produce a
        populated .mm.yml.  Otherwise produce a skeleton with placeholder CTRL /
        STATUS registers appropriate for the detected bus type.

        Args:
            ip_core: Parsed IP core model.
            discovered_regs: Optional list of memory-map dicts already in
                             .mm.yml structure (as returned by IpXactParser).

        Returns:
            YAML string suitable for writing to a .mm.yml file.
        """
        if discovered_regs:
            return self._generate_from_discovered(ip_core, discovered_regs)
        return self._generate_skeleton(ip_core)

    # ------------------------------------------------------------------
    # Skeleton generation
    # ------------------------------------------------------------------

    def _generate_skeleton(self, ip_core: IpCore) -> str:
        """Produce a placeholder .mm.yml with CTRL / STATUS registers."""
        name = ip_core.vlnv.name
        data = [
            {
                "name": "CSR_MAP",
                "description": "Control/Status Register Map",
                "addressBlocks": [
                    {
                        "name": "REGS",
                        "baseAddress": 0,
                        "usage": "register",
                        "defaultRegWidth": 32,
                        "registers": [
                            {
                                "name": "CTRL",
                                "description": "TODO: Control register",
                                "addressOffset": "0x0",
                                "fields": [
                                    {
                                        "name": "ENABLE",
                                        "bits": "[0:0]",
                                        "access": "read-write",
                                        "description": "Global enable (placeholder)",
                                    }
                                ],
                            },
                            {
                                "name": "STATUS",
                                "description": "TODO: Status register",
                                "addressOffset": "0x4",
                                "fields": [
                                    {
                                        "name": "READY",
                                        "bits": "[0:0]",
                                        "access": "read-only",
                                        "description": "Ready flag (placeholder)",
                                    }
                                ],
                            },
                        ],
                    }
                ],
            }
        ]

        header = (
            f"# Register map for {name}\n"
            "# Generated by ipcraft parse — populate with your register definitions\n"
        )
        return header + yaml.dump(
            data, default_flow_style=False, sort_keys=False, allow_unicode=True
        )

    # ------------------------------------------------------------------
    # Populated generation from discovered register data
    # ------------------------------------------------------------------

    def _generate_from_discovered(
        self,
        ip_core: IpCore,
        discovered_regs: List[Dict[str, Any]],
    ) -> str:
        """Produce a .mm.yml populated from IP-XACT register data."""
        name = ip_core.vlnv.name
        header = (
            f"# Register map for {name}\n"
            "# Generated by ipcraft parse from IP-XACT memory map\n"
        )
        return header + yaml.dump(
            discovered_regs,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )
