# Out-of-context timing constraints for led_controller_avmm
# Generated by IPCraft
#
# These constraints apply during OOC (out-of-context) synthesis and timing
# analysis.  Each create_clock call defines a clock period derived from the
# frequency specified in the .ip.yml definition.
#
# Adjust the -period values (in nanoseconds) if the target implementation
# frequency differs from the specification.

# clk — 50MHz
create_clock -period 20.000 -name clk [get_ports clk]
