# Vivado OOC synthesis runner for led_controller_avmm
# Generated by IPCraft
#
# Usage (from the xilinx/ directory):
#   vivado -mode batch -source led_controller_avmm_run_ooc.tcl -nojournal -nolog
#   vivado -mode batch -source led_controller_avmm_run_ooc.tcl -nojournal -nolog -tclargs 8
#
# Optional argument: number of parallel jobs (default 4).
# Reports are written to xilinx/build/ooc/.

set script_dir [file normalize [file dirname [info script]]]
set build_dir  [file join $script_dir build ooc]
set jobs       [expr {[llength $argv] > 0 ? int([lindex $argv 0]) : 4}]

puts "=== IPCraft: OOC Synthesis — led_controller_avmm ==="
puts "Build dir : $build_dir"
puts "Jobs      : $jobs"

# Create / refresh the OOC project (recreates build/ooc/ from scratch)
source [file join $script_dir led_controller_avmm_project.tcl]

# ---- Synthesis ----------------------------------------------------------
puts "\n--- Launching OOC synthesis ---"
launch_runs synth_1 -jobs $jobs
wait_on_run synth_1

set synth_status [get_property STATUS [get_runs synth_1]]
puts "Synthesis status: $synth_status"
if {[string match "*error*" [string tolower $synth_status]] || [get_property PROGRESS [get_runs synth_1]] ne "100%"} {
    puts "ERROR: Synthesis failed or did not complete successfully."
    exit 1
}

# ---- Reports ------------------------------------------------------------
puts "\n--- Generating reports ---"
open_run synth_1 -name synth_1

file mkdir $build_dir

report_timing_summary \
    -file            [file join $build_dir timing.rpt] \
    -warn_on_violation

report_utilization \
    -file            [file join $build_dir utilization.rpt]

catch {
    report_cdc -file [file join $build_dir cdc.rpt]
}

puts "\n=== OOC synthesis complete ==="
puts "Reports: $build_dir"
exit
